networks:
  prueba:
    name: prueba
    driver: bridge

services:
  # Database container
  postgres:
    image: postgres
    restart: always
    container_name: prueba.postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=prueba
    networks:
      - prueba

  # Pgadmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: prueba.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - postgres
    networks:
      - prueba
