networks:
  tudata:
    name: tudata
    driver: bridge

services:
  # Database container
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=tudata
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - tudata

  # Pgadmin
  pgadmin:
    image: teamidi/tudata_pgadmin:1.0
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "80:80"
    depends_on:
      - postgres
    networks:
      - tudata

  # Backend container
  tudata-backend:
    # Create backend container
    image: teamidi/tudata_backend:3.0
    ports:
      - "5000:5000"
    container_name: tudata.backend
    restart: always
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - tudata

  # Frontend container
  tudata-frontend: # Name of our service
    image: teamidi/tudata_frontend:3.0 # path to dockerfile
    ports: # Port binding to host from docker container
      - "10000:10000" # Bind port 3000 of host to 3000 of container
    container_name: tudata-frontend
    restart: always # What to do if container crashes
    links:
      - tudata-backend
    networks:
      - tudata

volumes:
    pgadmin:
    database:
